source 'https://rubygems.org'

gem 'sinatra', '~> 4.1'
gem 'rackup'
gem 'puma', '~> 6.6'
gem 'sinatra-contrib' # Para recarga en vivo
gem 'sinatra-activerecord' # Para ActiveRecord
gem 'sinatra-cross_origin'
gem 'sqlite3' # Para SQLite
gem 'rake' # Para tareas de base de datos
gem 'bcrypt'
gem 'prawn' # para pdf.

